### ISSUE TITLE
Link on the 418 page doesn't work

### ISSUE THREAD

**Issue by Bimi124** [libewa/libewa.github.io#1]
The link on `418.md` (`418.html` on the output weblite) doesn't work. The browser tells that the server wasn't found.

---

Tested with Chrome and Firefix.

**Comment by Bimi124** [comment]
p.S.: I could reach `google.com` normally...

**Comment by Bimi124** [comment]
solved it mysef. See https://github.com/libewa/libewa.github.io/compare/master...Bimi124:patch-1?expand=1

**Comment by libewa** [comment]
I wrote www_w_.google.com
