### ISSUE TITLE
Firefox warns me after the regridit

### ISSUE THREAD

**Issue by Bimi124** [libewa/libewa.github.io#3]
Firefox tells me your site would be risky.
I called https://libewa.github.io/. The regridit didn't work (maybie because it\`s "risky" so I clicked on the link to https://www.libewa.github.io/www and gor a warning. I removed `/www` manually so it and Firefox showed me the warning for your userpage again. After I hit sthe back button two times (one times for `https:\\www.libewa.github.io` and one times for `https://www.libewa.github.io/www`) the site wasn\`t risky. I think it\`s because the `www`... you use another subdomain...

**Comment by libewa** [comment]
It’s because the site has errors while editing. Don’t visit till I close this issue

**Comment by libewa** [comment]
There's only a pull request to accept, and the page works well!

**Comment by libewa** [comment]
> It’s because the site has errors while editing. Don’t visit till I close this issue

I said something bad! After looking at the file, I saw the link goes to `https://www.libewa.githu.io`
