### ISSUE TITLE
Sidenav does not work

### ISSUE THREAD

**Issue by libewa** [libewa/libewa.github.io#7]
The sidenav (wich appears with the **||| menu**-button) won't open.
The links on the main page aren't working too.

**Comment by Bimi124** [comment]
Hey! On Android & Firefox it works (but it looks a bit strange and someone could try to improve the links.

**Comment by libewa** [comment]
Say this the guys at W3Schools. They made this template for everyone to use.

**Comment by libewa** [comment]
> The sidenav (wich appears with the **||| menu**-button) won't open.
> The links on the main page aren't working too.

That's wrong. I meant, the Links aren't working, both in the sienav and on the main page

**Comment by libewa** [comment]
The link to `scratch.html` is wrong, I renamed the page.
And the folder `Hello_World` is now named `hello-world`
I'll rename them back and all is done
