### ISSUE TITLE
Stolen Images

### ISSUE THREAD

**Issue by Bimi124** [libewa/libewa.github.io#8]
Hey!
The images in `hntgrd` are stolen (I am the owner)! I could report you...

**Comment by Bimi124** [comment]
For everyone who is wondering how he got them: I tried to explain him a bit about CSS and added these Images for experimenting. Of corse I thaught he won't publish experiment and/or images.

**Comment by libewa** [comment]
Oops, I'll add you in the maker list

**Comment by libewa** [comment]
Created LICENSE.md with you

**Comment by libewa** [comment]
Everyone does sometimes something wrong. Can I still use the images? (Or I'll delete them they won't work)

**Comment by Bimi124** [comment]
Hey plese delete https://github.com/libewa/libewa.github.io/blob/master/hntgrd/wunderschoene_landschaft.jpg. That\`s my only wish. You could replace It with one of these awesome images: https://www.google.com/search?q=landscape&tbm=isch&safe=active&tbs=il:cl&hl=de&sa=X&ved=0CAAQ1vwEahcKEwjohMmOybntAhUAAAAAHQAAAAAQAg&biw=1349&bih=637

**Comment by libewa** [comment]
> Hey plese delete https://github.com/libewa/libewa.github.io/blob/master/hntgrd/wunderschoene_landschaft.jpg.

OK i'll do
